on: [push]
name: Deploy Bicep templte to Azure
permissions:
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
        
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          resourceGroupName: rg-bicep
          template: ./main.bicep
          parameters: storageName=storageBicepSna1979
          failOnStdErr: false
          
      
